#pragma once

#include <string_view>

namespace typecheck::error {
using namespace std::string_view_literals;

inline constexpr auto ERROR_MISSING_MAIN = "ERROR_MISSING_MAIN"sv;
inline constexpr auto ERROR_UNDEFINED_VARIABLE = "ERROR_UNDEFINED_VARIABLE"sv;
inline constexpr auto ERROR_UNEXPECTED_TYPE_FOR_EXPRESSION = "ERROR_UNEXPECTED_TYPE_FOR_EXPRESSION"sv;
inline constexpr auto ERROR_UNEXPECTED_LAMBDA = "ERROR_UNEXPECTED_LAMBDA"sv;
inline constexpr auto ERROR_UNEXPECTED_NUMBER_OF_PARAMS_IN_LAMBDA = "ERROR_UNEXPECTED_NUMBER_OF_PARAMS_IN_LAMBDA"sv;
inline constexpr auto ERROR_UNEXPECTED_TYPE_FOR_PARAMETER = "ERROR_UNEXPECTED_TYPE_FOR_PARAMETER"sv;
inline constexpr auto ERROR_NOT_A_FUNCTION = "ERROR_NOT_A_FUNCTION"sv;
inline constexpr auto ERROR_INCORRECT_NUMBER_OF_ARGUMENTS = "ERROR_INCORRECT_NUMBER_OF_ARGUMENTS"sv;
inline constexpr auto ERROR_DUPLICATE_FUNCTION_DECLARATION = "ERROR_DUPLICATE_FUNCTION_DECLARATION"sv;
inline constexpr auto ERROR_INCORRECT_ARITY_OF_MAIN = "ERROR_INCORRECT_ARITY_OF_MAIN"sv;
inline constexpr auto ERROR_UNEXPECTED_TUPLE = "ERROR_UNEXPECTED_TUPLE"sv;
inline constexpr auto ERROR_UNEXPECTED_TUPLE_LENGTH = "ERROR_UNEXPECTED_TUPLE_LENGTH"sv;
inline constexpr auto ERROR_NOT_A_TUPLE = "ERROR_NOT_A_TUPLE"sv;
inline constexpr auto ERROR_TUPLE_INDEX_OUT_OF_BOUNDS = "ERROR_TUPLE_INDEX_OUT_OF_BOUNDS"sv;
inline constexpr auto ERROR_UNEXPECTED_RECORD = "ERROR_UNEXPECTED_RECORD"sv;
inline constexpr auto ERROR_DUPLICATE_RECORD_FIELDS = "ERROR_DUPLICATE_RECORD_FIELDS"sv;
inline constexpr auto ERROR_UNEXPECTED_RECORD_FIELDS = "ERROR_UNEXPECTED_RECORD_FIELDS"sv;
inline constexpr auto ERROR_MISSING_RECORD_FIELDS = "ERROR_MISSING_RECORD_FIELDS"sv;
inline constexpr auto ERROR_NOT_A_RECORD = "ERROR_NOT_A_RECORD"sv;
inline constexpr auto ERROR_UNEXPECTED_FIELD_ACCESS = "ERROR_UNEXPECTED_FIELD_ACCESS"sv;
inline constexpr auto ERROR_UNEXPECTED_INJECTION = "ERROR_UNEXPECTED_INJECTION"sv;
inline constexpr auto ERROR_AMBIGUOUS_SUM_TYPE = "ERROR_AMBIGUOUS_SUM_TYPE"sv;
inline constexpr auto ERROR_UNEXPECTED_VARIANT = "ERROR_UNEXPECTED_VARIANT"sv;
inline constexpr auto ERROR_UNEXPECTED_VARIANT_LABEL = "ERROR_UNEXPECTED_VARIANT_LABEL"sv;
inline constexpr auto ERROR_MISSING_DATA_FOR_LABEL = "ERROR_MISSING_DATA_FOR_LABEL"sv;
inline constexpr auto ERROR_UNEXPECTED_DATA_FOR_NULLARY_LABEL = "ERROR_UNEXPECTED_DATA_FOR_NULLARY_LABEL"sv;
inline constexpr auto ERROR_AMBIGUOUS_VARIANT_TYPE = "ERROR_AMBIGUOUS_VARIANT_TYPE"sv;
inline constexpr auto ERROR_ILLEGAL_EMPTY_MATCHING = "ERROR_ILLEGAL_EMPTY_MATCHING"sv;
inline constexpr auto ERROR_NONEXHAUSTIVE_MATCH_PATTERNS = "ERROR_NONEXHAUSTIVE_MATCH_PATTERNS"sv;
inline constexpr auto ERROR_UNEXPECTED_PATTERN_FOR_TYPE = "ERROR_UNEXPECTED_PATTERN_FOR_TYPE"sv;
inline constexpr auto ERROR_UNEXPECTED_NON_NULLARY_VARIANT_PATTERN = "ERROR_UNEXPECTED_NON_NULLARY_VARIANT_PATTERN"sv;
inline constexpr auto ERROR_UNEXPECTED_NULLARY_VARIANT_PATTERN = "ERROR_UNEXPECTED_NULLARY_VARIANT_PATTERN"sv;
inline constexpr auto ERROR_UNEXPECTED_LIST = "ERROR_UNEXPECTED_LIST"sv;
inline constexpr auto ERROR_AMBIGUOUS_LIST_TYPE = "ERROR_AMBIGUOUS_LIST_TYPE"sv;
inline constexpr auto ERROR_NOT_A_LIST = "ERROR_NOT_A_LIST"sv;
inline constexpr auto ERROR_DUPLICATE_RECORD_TYPE_FIELDS = "ERROR_DUPLICATE_RECORD_TYPE_FIELDS"sv;
inline constexpr auto ERROR_DUPLICATE_VARIANT_TYPE_FIELDS = "ERROR_DUPLICATE_VARIANT_TYPE_FIELDS"sv;
inline constexpr auto ERROR_DUPLICATE_FUNCTION_PARAMETER = "ERROR_DUPLICATE_FUNCTION_PARAMETER"sv;

}
